### ISSUE TITLE
Bug in Tool_Get_num_Data_from_a_String.f

### ISSUE THREAD

**Issue by Beliavsky** [PhiPsi-Software/fortran_arithmetic#1]
In https://github.com/PhiPsi-Software/fortran_arithmetic/blob/main/src/Tool_Get_num_Data_from_a_String.f

I think 

```
      Yes_Even = .False.
      if(mod(num_Data,1)==0) Yes_Even = .True.
```

should be

```
      Yes_Even = .False.
      if(mod(num_Data,2)==0) Yes_Even = .True.
```

or more concisely

`      Yes_Even = mod(num_Data,2)==0`

**Comment by PhiPsi-Software** [comment]
Thanks, Beliavsky.
